# Generated by Django 2.0.2 on 2018-06-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
