# Generated by Django 2.0.2 on 2018-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Start Date')),
                ('start_time', models.TimeField(help_text='Starting time')),
                ('end_time', models.TimeField(help_text='Ending time')),
                ('notes', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('space', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
