# Generated by Django 2.0 on 2018-02-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180213_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, help_text='Venue Name', null=True),
        ),
    ]
