# Generated by Django 2.0.2 on 2018-06-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
