# Generated by Django 2.0 on 2018-02-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchvenuesugg',
            name='user',
        ),
        migrations.RenameField(
            model_name='searchbandsugg',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='band',
            name='social_media',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='searchVenueSugg',
        ),
    ]
