# Generated by Django 2.0 on 2018-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180219_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BandPictures',
        ),
    ]
