# Generated by Django 2.0 on 2018-02-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_delete_bandpictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbandsugg',
            name='username',
        ),
    ]
