# Generated by Django 2.0 on 2018-02-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_searchbandsugg_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbandsugg',
            name='username',
        ),
    ]
