# Generated by Django 2.0 on 2018-02-23 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='band',
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
