# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0018_band_bandpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchbandsugg',
            name='username',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
