# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_searchbandsugg_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
    ]
