# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='band',
        ),
        migrations.RemoveField(
            model_name='document',
            name='venue',
        ),
    ]
