# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180226_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbandsugg',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
