# Generated by Django 2.0.2 on 2018-02-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20180226_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbandsugg',
            name='username',
        ),
    ]
