# Generated by Django 2.0.2 on 2018-02-27 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_searchbandsugg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbandsugg',
            name='username',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
